### ISSUE TITLE
error in running

### ISSUE THREAD

**Issue by MRSheikh** [wannagotoberlin/file-system-pushyBoy#1]
hi
i run your code with this command
"sh run.sh"
but the permission error occurred. 
plz help me.

**Comment by wannagotoberlin** [comment]
Give execution permission to both run.sh as well as command_line_interface.
ie. on your terminal do `chmod +x run.sh` as well as `chmod +x command_line_interface`.
I'm guessing you forgot the second one.

**Comment by wannagotoberlin** [comment]
Let me know if it works!

**Comment by MRSheikh** [comment]
i tried it and `chmod 755` but those not work.
finally i removed  `command_line_interface` and then make it again. so that works fine.
thanks a lot for attention.
